### ISSUE TITLE
Make Eclipse remove trailing whitespace

### ISSUE THREAD

**Issue by salkinium** [roboterclubaachen/rca-vm#31]
There is no reason to add any.

If this is a default, users won't be able to add any.

**Comment by georgi-g** [comment]
http://stackoverflow.com/questions/1043433/how-to-auto-remove-trailing-whitespace-in-eclipse
http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_c_editor_save_actions.htm

**Comment by salkinium** [comment]
For the C/C++ Editor this already seems to be the standard behaviour.
But not for the Java or Python editor.
I can live with that.
