### ISSUE TITLE
Use faster DNS nameserver

### ISSUE THREAD

**Issue by salkinium** [roboterclubaachen/rca-vm#38]
This is probably a bug with virtualbox, but we should use something else than the local 10.0.2.3 DNS server.
Doing a `gits pull` using the default nameserver takes about 1m40s and with Google DNS it takes only about 0m7s.

That's a whopping 15x faster.

**Comment by georgi-g** [comment]
look here http://askubuntu.com/questions/201603/should-i-edit-my-resolv-conf-file-to-fix-wrong-dns-problem
