### ISSUE TITLE
Update Open OCD

### ISSUE THREAD

**Issue by georgi-g** [roboterclubaachen/rca-vm#48]
0.7.0 is too old.

**Comment by salkinium** [comment]
If the ubuntu package repository doesn't contain 0.9.0, then we need to install openocd from source again.
https://github.com/roboterclubaachen/rca-vm/blob/master/script/xpcc.sh#L31

**Comment by salkinium** [comment]
0.7.0 is way too old.

**Comment by salkinium** [comment]
Fixed in https://github.com/roboterclubaachen/rca-vm/commit/3e4ce891f5908887a836cff16050e94f3155300f
